# Generated by Django 4.0.4 on 2022-08-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название компании', max_length=50, verbose_name='Название компании')),
                ('country', models.CharField(help_text='Введите страну компании', max_length=50, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название консоли', max_length=50, verbose_name='Название консоли')),
                ('release_date', models.DateField(blank=True, help_text='Введите дату выхода консоли', null=True, verbose_name='Дата выхода консоли')),
                ('company', models.ForeignKey(help_text='Выберите компанию', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.company', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название жанра', max_length=50, verbose_name='Жанр игры')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название игры', max_length=100, verbose_name='Название игры')),
                ('release_date', models.DateField(blank=True, help_text='Введите дату выхода игры', null=True, verbose_name='Дата выхода игры')),
                ('picture', models.ImageField(upload_to='games/')),
                ('console', models.ForeignKey(help_text='Выберите консоль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.console', verbose_name='Консоль')),
                ('genre', models.ForeignKey(blank=True, help_text='Выберите жанр игры', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Жанр игры')),
            ],
        ),
    ]
