# Generated by Django 4.0.4 on 2022-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='...', upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='console',
            name='photo',
            field=models.ImageField(default='...', upload_to='consoles/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(default='...', upload_to='games/'),
        ),
    ]
