# Generated by Django 4.0.4 on 2022-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_company_logo_console_photo_alter_game_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название консоли', max_length=50, verbose_name='Название консоли')),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(blank=True, help_text='Введите описание консоли', null=True, verbose_name='Описание консоли')),
                ('photo', models.ImageField(blank=True, default='...', null=True, upload_to='news/')),
            ],
        ),
        migrations.AddField(
            model_name='console',
            name='text',
            field=models.TextField(help_text='Введите описание консоли', null=True, verbose_name='Описание консоли'),
        ),
    ]
