# Generated by Django 4.0.4 on 2022-09-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_news_options_alter_comments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesOfPhotoShoots',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('series_preview', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOfPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.seriesofphotoshoots')),
            ],
        ),
    ]
